[phases.setup]
aptPkgs = [
  "php-gd",
  "php-intl",
  "php-zip",
  "php-mbstring",
  "php-xml",
  "php-curl"
]

[build]
cmd = "composer install --no-interaction --prefer-dist --optimize-autoloader"

[start]
cmd = "php artisan config:cache && php artisan route:cache && php artisan serve --host=0.0.0.0 --port=${PORT}"
